-- Deleting existing PRODUCT table if any

DROP TABLE IF EXISTS PRODUCT CASCADE;

-- Create table
create table PRODUCT
(
  PRODUCT_ID        BIGINT not null,
  PRODUCT_NAME VARCHAR(128) not null,
  PRODUCT_PRICE   DOUBLE not null
) ;
--  
DROP TABLE IF EXISTS LAPTOP_CONFIGURATION  CASCADE;

-- Create table
create table LAPTOP_CONFIGURATION 
(
  LAPTOP_ID        BIGINT not null,
  LAPTOP_NAME VARCHAR(128) not null,
  LAPTOPOS VARCHAR(128) not null,
  LAPTOP_PROCESSOR VARCHAR(128) not null,
  LAPTOP_RAM   INT not null
) ;
--  

INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME , PRODUCT_PRICE ) VALUES ('6321', 'shampoo', '69.0');

INSERT INTO LAPTOP_CONFIGURATION (LAPTOP_ID,LAPTOP_NAME, LAPTOPOS,LAPTOP_PROCESSOR,LAPTOP_RAM ) VALUES ('1000', 'Lenovo', 'WIN10', 'INTEL','3' );

